kumuluzee:
  name: kumuluzee-jnosql-graph
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
  jnosql:
    column:
      config-class-name: org.jnosql.diana.cassandra.column.CassandraConfiguration

      cassandra-host-1: localhost
      cassandra-threads-number: 4
      key-space: 'developers'
      cassandra-query-1: "CREATE KEYSPACE IF NOT EXISTS developers WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};"
      cassandra-query-2: "CREATE COLUMNFAMILY IF NOT EXISTS developers.Oseba (id bigint PRIMARY KEY, ime text, phones list<text>);"
