kumuluzee:
  name: kumuluzee-jnosql-graph
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
  jnosql:
    column:
      config-class-name: org.jnosql.diana.cassandra.column.CassandraConfiguration

      cassandra-host-1: localhost
      cassandra-threads-number: 4
      key-space: 'developers'
      cassandra-query-1: "CREATE KEYSPACE IF NOT EXISTS developers WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};"
      cassandra-query-2: "CREATE COLUMNFAMILY IF NOT EXISTS developers.Person (id bigint PRIMARY KEY, name text, phones list<text>);"
#      cassandra-query-3: "CREATE TYPE IF NOT EXISTS developers.director (name text, movies set<text> );"
#      cassandra-query-4: "CREATE COLUMNFAMILY IF NOT EXISTS developers.Movie (name text PRIMARY KEY, age int,director FROZEN<director>);"
#      cassandra-query-5: "create index if not exists ageIndex on developers.movie(age);"
