version: '3'
services:
  neo4j:
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    image: neo4j:latest
    container_name: 'neo4j'
  janusgraph:
    restart: always
    ports:
      - 8182:8182
    image: janusgraph/janusgraph:latest
    container_name: 'janusgraph'
  mongo:
    container_name: 'mongodb'
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
