version: '3.7'
services:
  neo4j:
    ports:
      - 7474:7474
      - 7687:7687
    image: neo4j:3.5
    container_name: 'neo4j'

  janusgraph:
    ports:
      - 8182:8182
    image: janusgraph/janusgraph:0.5.2
    container_name: 'janusgraph'

  mongo:
    ports:
      - 10000:27017
    image: mongo:4.4.0-rc9
    container_name: 'mongodb'

  hazelcast:
    ports:
      - 5701:5701
    image: hazelcast/hazelcast:4.0.1
    container_name: 'hazelcast'

  redis:
    ports:
      - 6379:6379
    image: redis:6.0.5
    container_name: 'redis'

  cassandra:
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9060
    image: cassandra:latest
    container_name: 'cassandra'

